export enum AuditAction {
  // Authentication & Security Governance Actions
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  ROLE_VERIFIED = 'ROLE_VERIFIED',
  RBAC_ACCESS_DENIED = 'RBAC_ACCESS_DENIED',
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  ADMIN_ACCESS_ATTEMPT = 'ADMIN_ACCESS_ATTEMPT',
  SAFETY_EVENT_TRIGGERED = 'SAFETY_EVENT_TRIGGERED',

  // Phase 2 Canonical Authentication Audit Actions
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ROLE_CHANGE_REJECTED = 'ROLE_CHANGE_REJECTED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // Phase 6 Guardian System Audit Actions
  GUARDIAN_INVITATION_CREATED = 'GUARDIAN_INVITATION_CREATED',
  GUARDIAN_INVITATION_ACCEPTED = 'GUARDIAN_INVITATION_ACCEPTED',
  GUARDIAN_INVITATION_DECLINED = 'GUARDIAN_INVITATION_DECLINED',
  GUARDIAN_RELATIONSHIP_REVOKED = 'GUARDIAN_RELATIONSHIP_REVOKED',
  GUARDIAN_DISCONNECTED = 'GUARDIAN_DISCONNECTED',
  GUARDIAN_PREFERENCES_UPDATED = 'GUARDIAN_PREFERENCES_UPDATED',
  GUARDIAN_ACCESS_DENIED = 'GUARDIAN_ACCESS_DENIED',

  // Phase 7 Admin System Audit Actions
  ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS',
  ADMIN_USER_STATUS_UPDATED = 'ADMIN_USER_STATUS_UPDATED',
  ADMIN_USER_ROLE_UPDATED = 'ADMIN_USER_ROLE_UPDATED',
  ADMIN_ROLE_CHANGE_REJECTED = 'ADMIN_ROLE_CHANGE_REJECTED',
  ADMIN_SYSTEM_CONFIG_UPDATED = 'ADMIN_SYSTEM_CONFIG_UPDATED',
  ADMIN_ACCESS_DENIED = 'ADMIN_ACCESS_DENIED',
}

export interface AuditLogEntry {
  id: string;
  userId?: string | null;
  action: AuditAction;
  entityType?: string;
  entityId?: string;
  metadata?: Record<string, unknown>;
  ipAddress?: string;
  userAgent?: string;
  timestamp: string;
}
